export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const MEDICINE_lOADING = 'MEDICINE_lOADING';
export const MEDICINE_ERROR = 'MEDICINE_ERROR';
export const MEDICINE_SUCCESS = 'MEDICINE_SUCCESS';
export const MEDICINE_ADD = 'MEDICINE_ADD';
export const MEDICINE_DELETE = 'MEDICINE_DELETE';
export const MEDICINE_UPDATE = 'MEDICINE_UPDATE';

export const Add_TO_CART = 'Add_TO_CART';
export const INCREMENT_QUANTITY = 'INC_QUNTITY';
export const DECREMENT_QUANTITY = 'DEC_QUNTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_TO_FAVOURITE = 'REMOVE_TO_FAVOURITE';

export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENT_ERROR= "DEPARTMENT_ERROR";
export const DEPARTMENT_GET = "DEPARTMENT_GET";
export const DEPARTMENT_ADD = "DEPARTMENT_ADD";
export const DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
export const DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE";

export const DOCTORS_lOADING = 'DOCTORS_lOADING';
export const DOCTORS_ERROR = 'DOCTORS_ERROR';
export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
export const DOCTORS_ADD = 'DOCTORS_ADD';
export const DOCTORS_DELETE = 'DOCTORS_DELETE';
export const DOCTORS_UPDATE = 'DOCTORS_UPDATE';

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGGED_IN = 'LOGGED_IN';
export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_RESPONSE = "FORGOT_RESPONSE"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGGED_OUT = "LOGGED_OUT";
export const AUTH_ERROR = "AUTH_ERROR";